import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";
import { Josefin_Sans } from "next/font/google";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Caffe del 900' ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${josefin.className}`}>
        <Header />
        
          <main>{children}</main>
        
      </body>
    </html>
  );
}
