import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";
import { Poppins } from "next/font/google";

const josefin = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600"],
});

export const metadata = {
  title: "Caffe del 900' ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${josefin.className}`}>
        <Header />

        <main>{children}</main>
      </body>
    </html>
  );
}
